class DataConfig:
    data_file_path = "./data/gaussian_4d_independent_set12_samples.csv"
    processed_data_prefix = "gaussian_independent_set12"
    columns = ['x1', 'x2']
    # mxbins = 300j # Number of bins for marginal distributions
    # cxbins = 300j # Number of bins for conditional distributions
    jxbins = 400j # Number of bins for joint distribution
    # b_adj_m = 1.0 # Bandwidth adjustment for KDE adjustment factor on scott's factor for the bandwidth
    # b_adj_c = 1.0
    bw_adj_joint_range = (0.4, 1.2) # Range for bandwidth adjustment for joint distribution KDE
    cv_intervals = 11 # Number of intervals for cross-validation
    kernel_type = 'gaussian' # Kernel type for KDE
    reflection_lines = None
    truncate_range = None
    # slice_num = 10 # Number of slices for conditional distributions
    grid_tolerance = 1e-3 # Tolerance for grid generation
    filter = False
    filter_threshold = None # Threshold for filtering out low probability values
    domain_estimation = False # Whether to estimate the domain of the data
    # domain_factor = 0.9 # Factor to adjust the domain estimation
    domain_shrink_offset = 1 # Offset to shrink the domain
    # left_exfactor = 1.0 # Factor to shrink the left domain
    # right_exfactor = 1.0 # Factor to shrink the right domain
    slices = [slice(-4.0, 12.0, jxbins), slice(-12.0, 4.0, jxbins)]
    density_range_scaling_target = 10.0
    min_max_scaling = False
    lr=5e-4
